---
AWSTemplateFormatVersion: '2010-09-09'
Description: ansible Code Deploy


####### Services creation #########
Resources:
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: baseApp

  CodeDeployAppDeploy:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      AutoScalingGroups:
      - !ImportValue AutoScaling

      DeploymentGroupName: Staging
      Deployment:
        Description: "A base App"
        IgnoreApplicationStopFailures: true
        Revision:
          RevisionType: GitHub
          GitHubLocation:
            CommitId: c73dc1438f5b74134a5f04caf98dbf5f71d68750
            Repository: rschmidtz/baseApp
      ServiceRoleArn: !ImportValue CodeDeployRole


######### Outputs ##########
Outputs:
  Url:
    Description: CodeDeploy
    Value: !Ref CodeDeployAppDeploy
